<?php
/** @file
 * Configuration file for viewgit.
 *
 * @note DO NOT EDIT THIS FILE. Create localconfig.php instead and override the settings in it.
 */
$conf['projects'] = array(
	// 'name' => array('repo' => '/path/to/repo'),
);

$conf['datetime'] = '%Y-%m-%d %H:%M:%S';

include_once('localconfig.php');
